In [1]:
import numpy as np
import matplotlib.pyplot as plt
import qutip as qt

In [41]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)
print(np.dot(a, b))
print(np.sum(np.dot(a, b)))

[[0.51036352 0.42783457]
 [0.28632185 0.29924064]]
1.5237605802200722


In [42]:
def psi_M(S, w):
    """Returns a component of a wavefunciton
    in the S direction"""
    a, b, W = w[0], w[1], w[2]
    psi = np.exp(np.sum(np.dot(a, S)))
    for i in range(len(W)):
        Fi = 2 * np.cosh(b[i] + np.sum(np.dot(W[i], S)))
        psi *= Fi
    return psi

def psi(w):
    N = len(w[0])
    psi = np.zeros((2,2))
    psi[0, 0] = psi_M((0, 0), w)
    psi[0, 1] = psi_M((0, 1), w)
    psi[1, 0] = psi_M((1, 0), w)
    psi[1, 1] = psi_M((1, 1), w)
    return psi

def show_psi(psi):
    """psi is an 2x2 array for now
    in general it will be N^N array"""
    s = 'psi = '
    for i in range(len(psi)):
        for j in range(len(psi[i])):
            s += str('%.2f' % psi[i,j]) + '|' + str(i) + str(j) + '>' + ' + '
    return s[:-3]

def sigma_x(psi):
    psi1 = np.zeros((len(psi), len(psi)))
    for i in range(len(psi)):
        for j in range(len(psi[i])):
            psi1[(i + 1) % 2, j] += psi[i, j]
            psi1[i, (j + 1) % 2] += psi[i, j]
    return psi1

def sign(i):
    return 1 if i == 1 else -1

def sigma_z(psi):    # not working well probs
    psi1 = np.zeros((len(psi), len(psi)))
    for i in range(len(psi)):
        for j in range(len(psi[i])):
            psi1[i, j] = (-1) ** (i + j) * psi[i, j]
    return psi1

def hamiltonian(psi):
    return sigma_z(psi) + sigma_x(psi)

def avg_energy(psi, ham):
    """Returns the average energy for a given  wavefunciton
    and a given hamiltonian
    <E> = <psi|H|psi> / <psi|psi>"""
    psi_star = np.conjugate(psi)
    return np.sum(np.dot(psi_star, hamiltonian(psi))) / np.sum(np.dot(psi_star, psi))
    

# def hamiltonian2(psi):    # verifying if the terms commute
#     return sigma_x(psi) + sigma_z(psi)

In [43]:
a = 1,1
b = 2,3
W = np.random.rand(2,2)
w = a, b, W
S = 1, 1
psi_M(S, w)
p = psi(w)
h = hamiltonian(p)
E = avg_energy(p, h)

In [44]:
print(show_psi(p))
print(h)
print(E)

psi = 151.51|00> + 991.36|01> + 432.62|10> + 2834.02|11>
[[1575.48239341 1994.16758995]
 [2552.90190784 4257.99319321]]
2.1376494857503032


In [77]:
psi = np.random.rand(2,2)
show_psi(psi)

'psi = 0.85|00> + 0.90|01> + 0.50|10> + 0.67|11>'

In [78]:
psi1 = sigma_x(psi)
psi2 = sigma_z(psi)

In [79]:
show_psi(psi1)
show_psi(psi2)

'psi = 0.85|00> + -0.90|01> + -0.50|10> + 0.67|11>'

In [80]:
h1 = hamiltonian(psi)
h2 = hamiltonian2(psi)

In [81]:
h1

array([[2.24603489, 0.61458561],
       [1.01946406, 2.06211707]])

In [82]:
h2

array([[2.24603489, 0.61458561],
       [1.01946406, 2.06211707]])